services:
  - type: web
    name: bitcoin-analyzer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bwss.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /health