services:
  - type: web
    name: bitcoin-analyzer-bot
    env: python
    region: frankfurt  # Türkiye'ye yakın region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bwss.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        value: "7715414446:AAGDvt3TiyjZxWAr6NzY8CN5qQf0_fy4PWw"
        sync: false
    # Free plan için önemli ayarlar
    disk:
      name: data
      mountPath: /data
      sizeGB: 1